apiVersion: v1
kind: Service
metadata:
 name: mysvc2
spec:
 type: NodePort  # type of service
 selector: # endpints selector
  type: webserver
 ports:
  - port: 80 # service port
    targetPort: 80 # container Image port
